name: Build and Deploy Eleventy Site

# Only run on manual trigger for now to avoid breaking the site
on:
  workflow_dispatch:
  # Uncomment the lines below once we've tested the deployment
  # push:
  #   branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Add the required environment for GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Eleventy site
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
